import = ["~/.config/alacritty/themes/default.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"
# macOS
# SHELL = "/opt/homebrew/bin/bash"

# Windows
# [shell]
# program = "wsl.exe"
# args = ["~"]

[window]
decorations = "none"
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[font]
size = 11.5

[font.normal]
family = "MesloLGM Nerd Font"
style = "Regular"

[font.bold]
style = "Regular"

[cursor.style]
blinking = "Off"
shape = "Block"

[selection]
save_to_clipboard = true

[[mouse.bindings]]
action = "Paste"
mouse = "Right"
