colors:
  primary:
    background: '0x1f2329'
    foreground: '0xd9d9d9'

  cursor:
    text: '0x000000'
    cursor: '0xffffff'

  selection:
    text: '0x000000'
    background: '0xfffacd'

  normal:
    black:   '0x000000'
    red:     '0xd54e53'
    green:   '0xb9ca4a'
    yellow:  '0xe6c547'
    blue:    '0x7aa6da'
    magenta: '0xc397d8'
    cyan:    '0x70c0ba'
    white:   '0xeaeaea'

  bright:
    black:   '0x666666'
    red:     '0xff3334'
    green:   '0x9ec400'
    yellow:  '0xe7c547'
    blue:    '0x7aa6da'
    magenta: '0xb77ee0'
    cyan:    '0x54ced6'
    white:   '0xffffff'

  dim:
    black:   '0x000000'
    red:     '0x8c3336'
    green:   '0x7a8530'
    yellow:  '0x97822e'
    blue:    '0x506d8f'
    magenta: '0x80638e'
    cyan:    '0x497e7a'
    white:   '0x9a9a9a'
