alias cls='clear'
alias curlx='curl -x proxy.example.com:8080'
alias e.='explorer.exe .'
alias gb='git branch -vv'
alias glog='git log --graph --decorate --oneline'
alias gs='git status'
alias gtop='cd `git rev-parse --show-toplevel`'
alias k='kubectl'
alias ls='ls -lah --color=auto'
alias mvnfull='mvn clean install -PautoInstallSinglePackage'
alias mvnquick='mvn clean install -PautoInstallBundle -DskipTests -Dcheckstyle.skip=true -Dpmd.skip=true -Dfindbugs.skip=true -Dspotbugs.skip=true'
alias npp='notepad++.exe'
alias pwsh='pwsh.exe'
alias upd='sudo apt update && sudo apt upgrade -y'
