alias e.='explorer.exe .'
alias glog='git log --graph --decorate --oneline'
alias gs='git status'
alias gtop='cd `git rev-parse --show-toplevel`'
alias home='cd /mnt/c/Users/khoa/'
alias ls='ls -lah --color=auto'
alias upd='sudo apt update && sudo apt upgrade -y'
